#!/usr/bin/env python3
"""
Generate Darcy Flow dataset for PINO phase-plot experiments.

PDE: -∇·(a(x)∇u(x)) = f (default f=1),  x ∈ (0,1)²,  u=0 on ∂(0,1)²

a(x) is piecewise-constant, generated by thresholding a 2D Gaussian
Random Field (matching the original piececonst paper setup):

    z ~ GRF(N(0, (-Δ + τ²I)^{-α}))   on (0,1)²
    a(x) = a_high  if z(x) >= 0
           a_low   otherwise

For comparison with the original piececonst dataset: a_low=3, a_high=12, r=4.

The FDM solver uses a 5-point stencil with arithmetic-mean interface
coefficients, assembled as a vectorised sparse matrix and solved with
scipy.sparse.linalg.spsolve (UMFPACK direct solver).

Usage
-----
# Quick validation: r=4, N=421, n=1024 → should reproduce ~0.73% PINO error
python generate_darcy.py --N 421 --n_samples 1024 --r 4 --seed 0 \
    --outdir /pscratch/sd/w/wyx345/pino/darcy_gen

# Phase-plot sweep: r=2,4,8,32,128
for r in 2 4 8 32 128; do
  python generate_darcy.py --N 421 --n_samples 1024 --r $r --seed 0 \
      --outdir /pscratch/sd/w/wyx345/pino/darcy_gen
done
"""

import argparse, os, sys, time
import numpy as np
import scipy.io
import scipy.sparse as sp
import scipy.sparse.linalg as spla
import torch

import math as _math
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


# ──────────────────────────────────────────────────────────────────
# 1.  Coefficient field generation  (supports any N, odd or even)
# ──────────────────────────────────────────────────────────────────

def gen_coeff(N: int, n_samples: int, r: float,
              tau: float = 3.0, alpha: float = 2.0,
              a_low: float = 3.0, sigma_scale: float = 1.0,
              seed: int = 0) -> np.ndarray:
    """
    Generate n_samples piecewise-constant fields a(x) ∈ {a_low, r*a_low}.

    Parameters match the original piececonst dataset exactly when
    tau=3, alpha=2, a_low=3, r=4  →  a ∈ {3, 12}.

    Works for any N (odd or even) via rfft2.
    The GRF covariance is (-Δ + τ²I)^{-α} on [0,1]², matching the paper:
      µ = ψ#N(0, (-Δ + 9I)^{-2})
    """
    torch.manual_seed(seed)

    # Integer wavenumbers for [0,1]^2 domain (via DFT frequencies × N)
    k1 = torch.fft.fftfreq(N).float() * N     # shape (N,)
    k2 = torch.fft.rfftfreq(N).float() * N    # shape (N//2+1,)
    K1, K2 = torch.meshgrid(k1, k2, indexing='ij')  # (N, N//2+1)

    # Spectral square-root of covariance:
    #   sqrt_eig ∝ (4π²|k|² + τ²)^{-α/2}
    # Normalisation N·√2·σ matches GaussianRF(dim=2, length=1, size=N).
    const = 4.0 * (_math.pi ** 2)
    sigma = tau ** (0.5 * (2 * alpha - 2)) * float(sigma_scale)  # base σ × user scale
    sqrt_eig = (N * _math.sqrt(2.0) * sigma *
                ((const * (K1**2 + K2**2) + tau**2) ** (-alpha / 2.0)))
    sqrt_eig[0, 0] = 0.0                        # zero mean

    # Sample complex Gaussian noise, filter, transform to real space
    xi = torch.randn(n_samples, N, N // 2 + 1, dtype=torch.cfloat)
    xi = xi * sqrt_eig.unsqueeze(0)
    z = torch.fft.irfft2(xi, s=(N, N)).numpy()  # (n_samples, N, N)

    a_high = a_low * r
    return np.where(z >= 0, a_high, a_low).astype(np.float64)


# ──────────────────────────────────────────────────────────────────
# 2.  FDM sparse-matrix assembly (vectorised)
# ──────────────────────────────────────────────────────────────────

def build_fdm_matrix(a: np.ndarray, N: int, f: float = 1.0):
    """
    Build sparse FDM matrix for -∇·(a∇u) = f (constant source on interior).

    Interior nodes only (Dirichlet BC u=0 on boundary).
    Row-major ordering: k = (i-1)*(N-2) + (j-1), i,j ∈ {1,...,N-2}.

    Returns
    -------
    A  : (n²×n²) CSR sparse matrix   where n = N-2
    rhs: (n²,) each entry = f (discrete RHS for constant f in this scaling)
    """
    h   = 1.0 / (N - 1)
    n   = N - 2
    n2  = n * n
    ih2 = 1.0 / h**2

    # Vectorised interface coefficients on interior block
    a_ip = 0.5 * (a[1:N-1, 1:N-1] + a[2:N,   1:N-1]) * ih2  # east  a_{i+½,j}
    a_im = 0.5 * (a[1:N-1, 1:N-1] + a[0:N-2, 1:N-1]) * ih2  # west
    a_jp = 0.5 * (a[1:N-1, 1:N-1] + a[1:N-1, 2:N  ]) * ih2  # north a_{i,j+½}
    a_jm = 0.5 * (a[1:N-1, 1:N-1] + a[1:N-1, 0:N-2]) * ih2  # south

    # Row-major index grid
    Igrid, Jgrid = np.meshgrid(np.arange(1, N-1),
                                np.arange(1, N-1), indexing='ij')  # (n,n)
    K = (Igrid - 1) * n + (Jgrid - 1)   # flat interior index (n,n)

    row_list = [K.ravel()]
    col_list = [K.ravel()]
    dat_list = [(a_ip + a_im + a_jp + a_jm).ravel()]   # diagonal

    # South neighbour  (i+1, j) : row K, col K+n  — valid when i < N-2
    m = Igrid < N - 2
    row_list.append(K[m]); col_list.append(K[m] + n)
    dat_list.append(-a_ip[m])

    # North neighbour (i-1, j) : row K, col K-n  — valid when i > 1
    m = Igrid > 1
    row_list.append(K[m]); col_list.append(K[m] - n)
    dat_list.append(-a_im[m])

    # East neighbour  (i, j+1) : row K, col K+1  — valid when j < N-2
    m = Jgrid < N - 2
    row_list.append(K[m]); col_list.append(K[m] + 1)
    dat_list.append(-a_jp[m])

    # West neighbour  (i, j-1) : row K, col K-1  — valid when j > 1
    m = Jgrid > 1
    row_list.append(K[m]); col_list.append(K[m] - 1)
    dat_list.append(-a_jm[m])

    rows = np.concatenate(row_list).astype(np.int32)
    cols = np.concatenate(col_list).astype(np.int32)
    data = np.concatenate(dat_list)

    A   = sp.csr_matrix((data, (rows, cols)), shape=(n2, n2))
    rhs = np.ones(n2, dtype=np.float64) * f
    return A, rhs


def solve_darcy_batch(a_batch: np.ndarray, N: int, f: float = 1.0) -> np.ndarray:
    """
    Solve -∇·(a∇u) = f for a batch of coefficient fields (constant f).

    Parameters
    ----------
    a_batch : (B, N, N) float64 array
    N       : grid size (including boundary nodes)

    Returns
    -------
    u_batch : (B, N, N) float64, u=0 on boundary
    """
    B = a_batch.shape[0]
    n = N - 2
    u_batch = np.zeros((B, N, N), dtype=np.float64)

    t0 = time.time()
    for idx in range(B):
        A, rhs = build_fdm_matrix(a_batch[idx], N, f=f)
        u_int  = spla.spsolve(A, rhs)             # (n²,)
        u_batch[idx, 1:N-1, 1:N-1] = u_int.reshape(n, n)

        if (idx + 1) % max(1, B // 10) == 0:
            elapsed = time.time() - t0
            eta = elapsed / (idx + 1) * (B - idx - 1)
            print(f'  [{idx+1:4d}/{B}]  elapsed {elapsed:.0f}s  ETA {eta:.0f}s',
                  flush=True)

    return u_batch


# ──────────────────────────────────────────────────────────────────
# 3.  Main
# ──────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--N',         type=int,   default=421,
                        help='FDM grid size. 421 matches the piececonst dataset '
                             'exactly (use sub=7 when training → 61×61).')
    parser.add_argument('--n_samples', type=int,   default=1024)
    parser.add_argument('--r',         type=float, default=4.0,
                        help='Contrast ratio a_high/a_low. '
                             'r=4 reproduces piececonst {3,12}.')
    parser.add_argument('--a_low',     type=float, default=3.0,
                        help='Low diffusion coefficient. Default 3.')
    parser.add_argument('--tau',       type=float, default=3.0)
    parser.add_argument('--alpha',     type=float, default=2.0)
    parser.add_argument(
        '--sigma-scale',
        type=float,
        default=1.0,
        help='Multiplier on GRF sigma normalisation (default 1.0). '
             'With z>=0 thresholding this mainly rescales amplitude.',
    )
    parser.add_argument(
        '--f',
        type=float,
        default=1.0,
        help='Constant forcing in -∇·(a∇u)=f (discrete rhs scaled accordingly). Default 1.',
    )
    parser.add_argument('--seed',      type=int,   default=0)
    parser.add_argument('--outdir',    type=str,
                        default='/pscratch/sd/w/wyx345/pino/darcy_gen')
    args = parser.parse_args()

    os.makedirs(args.outdir, exist_ok=True)
    legacy_nm = (
        abs(args.tau - 3.0) < 1e-12
        and abs(args.alpha - 2.0) < 1e-12
        and abs(args.a_low - 3.0) < 1e-12
        and abs(args.sigma_scale - 1.0) < 1e-12
    )
    if legacy_nm:
        fname = (
            f"darcy_N{args.N}_n{args.n_samples}_r{args.r:.0f}_f{args.f:g}_seed{args.seed}.mat"
        )
    else:
        tt = f"{float(args.tau):g}".replace("-", "m")
        at = f"{float(args.alpha):g}".replace("-", "m")
        alt = f"{float(args.a_low):g}".replace("-", "m")
        sgt = f"{float(args.sigma_scale):g}".replace("-", "m")
        fname = (
            f"darcy_N{args.N}_n{args.n_samples}_r{args.r:.0f}_f{args.f:g}_"
            f"tau{tt}_a{at}_al{alt}_sg{sgt}_seed{args.seed}.mat"
        )
    fpath = os.path.join(args.outdir, fname)

    if os.path.exists(fpath):
        sz = os.path.getsize(fpath)
        print(f'Already exists: {fpath}  ({sz/1e6:.0f} MB)')
        return

    print(f'Generating Darcy data:')
    print(
        f'  N={args.N}  n_samples={args.n_samples}  r={args.r}  f={args.f}  '
        f'a∈{{{args.a_low:.0f},{args.a_low*args.r:.0f}}}  '
        f'sigma_scale={args.sigma_scale:g}  seed={args.seed}'
    )

    t0 = time.time()
    print('  Step 1: GRF coefficient fields...', flush=True)
    a = gen_coeff(
        N=args.N,
        n_samples=args.n_samples,
        r=args.r,
        tau=args.tau,
        alpha=args.alpha,
        a_low=args.a_low,
        sigma_scale=args.sigma_scale,
        seed=args.seed,
    )
    print(f'  a={a.shape}  range=[{a.min():.1f}, {a.max():.1f}]  '
          f'({time.time()-t0:.1f}s)', flush=True)

    print(f'  Step 2: FDM solve ({args.n_samples} systems, N={args.N})...', flush=True)
    t1 = time.time()
    u = solve_darcy_batch(a, args.N, f=args.f)
    print(f'  u={u.shape}  range=[{u.min():.5f}, {u.max():.5f}]  '
          f'({time.time()-t1:.1f}s)', flush=True)

    print(f'  Step 3: Saving → {fpath}', flush=True)
    scipy.io.savemat(
        fpath,
        {
            'coeff': a.astype(np.float64),
            'sol': u.astype(np.float64),
            'f': float(args.f),
            'tau': float(args.tau),
            'alpha': float(args.alpha),
            'a_low': float(args.a_low),
            'sigma_scale': float(args.sigma_scale),
        },
        do_compression=True,
    )
    sz = os.path.getsize(fpath)
    print(f'  Done. {sz/1e6:.0f} MB  total {time.time()-t0:.0f}s')


if __name__ == '__main__':
    main()
